version: '3.9'

services:
  app:
    container_name: typeorm_migrations
    build: .
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules/
    networks:
      - typeorm_migrations_network
    ports:
      - 3000:3000
    depends_on:
      - database
  database:
    image: postgres:15.3-alpine3.18
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=typeorm_migrations
    networks:
      - typeorm_migrations_network

networks:
  typeorm_migrations_network:
    driver: bridge